// 公共组件导出总线
// export { default as vTree } from './v-tree'
// export const tranfer = require('./tranfer').default
export { default as ansoTreeSelect } from './anso-tree-select'
export { default as ansoDatePicker } from './anso-date-picker'
export { default as ansoButton } from './anso-button'
export { default as ansoTree } from './anso-tree'
export { default as ansoSidebar } from './anso-sidebar'
export { default as ansoForm } from './anso-form'
export { default as tableForm } from './table-form'
export { default as tableTools } from './table-tools'
export { default as tableHead } from './table-head'
export { default as ansoTable } from './anso-table'
export { default as tablePage } from './table-page'
export { default as ansoModal } from './anso-modal'
