// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StylesLessNamespace {
  export interface IStylesLess {
    root: string;
  }
}

declare const StylesLessModule: StylesLessNamespace.IStylesLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesLessNamespace.IStylesLess;
};

export = StylesLessModule;
