// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AppLessNamespace {
  export interface IAppLess {
    container: string;
  }
}

declare const AppLessModule: AppLessNamespace.IAppLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AppLessNamespace.IAppLess;
};

export = AppLessModule;
